# Generated by Django 2.0.3 on 2018-09-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree_plan_code',
            field=models.TextField(blank=True),
        ),
    ]
