# Generated by Django 2.0.4 on 2018-04-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousStudentDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('courses_taken', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='degree',
            name='description',
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
