# Generated by Django 2.0.4 on 2018-08-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0004_degreeplanstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DegreePlanStore',
        ),
    ]
