# Generated by Django 2.1.1 on 2018-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0005_delete_degreeplanstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2014', '2014'), ('2015', '2015'), ('2016', '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default='2019', max_length=4)),
                ('code', models.CharField(default='none', max_length=6)),
                ('name', models.CharField(max_length=60)),
                ('units', models.CharField(default='000', max_length=3)),
                ('compulsary_courses', models.ForeignKey(on_delete='Cascade', to='degree.Course')),
            ],
        ),
    ]
