# Generated by Django 2.0.3 on 2018-09-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0005_delete_degreeplanstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreePlanStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('plan', models.TextField()),
            ],
        ),
    ]
