# Generated by Django 2.1.1 on 2018-10-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0006_course_degreeplanstore_degreerequirement'),
        ('degree', '0006_degreeplanstore'),
    ]

    operations = [
    ]
