# Generated by Django 2.1.1 on 2018-10-02 02:34

from django.db import migrations, models





class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0007_merge_20181001_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreerequirement',
            name='compulsary_courses',
        ),
        migrations.AddField(
            model_name='degreerequirement',
            name='required',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='year',
            field=models.CharField(choices=[('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2019', max_length=4),
        ),
    ]


