# Generated by Django 2.1.1 on 2018-10-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0008_auto_20181002_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='course',
            name='outcome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisite_cnf',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='units',
            field=models.CharField(default='', max_length=3),
        ),
    ]
