# Generated by Django 2.1.1 on 2018-10-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0009_auto_20181004_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='pre_requisite_cnf',
            new_name='prerequisite_cnf',
        ),
    ]
