# Generated by Django 2.1.1 on 2018-10-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0010_auto_20181004_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
