# Generated by Django 2.1.1 on 2018-10-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0011_remove_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequisite_cnf',
            new_name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='outcome',
        ),
        migrations.AddField(
            model_name='course',
            name='conviener',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='graduation_stage',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default='Undergraduate', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
