# Generated by Django 2.1.1 on 2018-10-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0012_auto_20181004_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='conviener',
            new_name='convener',
        ),
    ]
