# Generated by Django 2.1.1 on 2018-10-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0013_auto_20181004_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='convener',
            new_name='convenor',
        ),
    ]
