# Generated by Django 2.1.1 on 2018-10-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0014_auto_20181004_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='es_id',
            field=models.CharField(db_index=True, default='', editable=False, max_length=10),
        ),
    ]
