# Generated by Django 2.1.1 on 2018-10-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0015_course_es_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=9),
        ),
    ]
