# Generated by Django 2.1.1 on 2018-10-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0017_auto_20181005_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='incompatible',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, default='', editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, default='', editable=False, max_length=4),
        ),
    ]
