# Generated by Django 2.1.1 on 2018-10-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0020_auto_20181006_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='learning_outomes',
            new_name='learning_outcomes',
        ),
    ]
