# Generated by Django 2.1.1 on 2018-10-07 13:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0025_remove_course_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
