# Generated by Django 2.1.1 on 2018-10-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0026_course_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='data',
        ),
    ]
