# Generated by Django 2.1.1 on 2018-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0027_remove_course_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='convenor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
    ]
