# Generated by Django 2.1.1 on 2018-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0028_auto_20181007_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
