# Generated by Django 2.1.1 on 2018-10-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0030_auto_20181007_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreerequirement',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
