# Generated by Django 2.1.1 on 2018-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0031_auto_20181007_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreerequirement',
            name='units',
            field=models.CharField(default='', max_length=10),
        ),
    ]
