# Generated by Django 2.0.7 on 2018-10-08 05:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0035_remove_course_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('year', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], default='undergraduate', max_length=60)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='required',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
