# Generated by Django 2.0.7 on 2018-10-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0037_auto_20181008_0520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
