# Generated by Django 2.0.7 on 2018-10-08 05:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0040_auto_20181008_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreerequirement',
            name='required',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='major',
            name='requirements',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
